working menu-maker TUI, but need to fix for using with other scripts
note: need to write UI to stderr, and final output to stdin

diff --git a/bin/menu-maker b/bin/menu-maker
--- a/bin/menu-maker
+++ b/bin/menu-maker
@@ -8,115 +8,17 @@
 # `--all-checked` checks all items in the list.
 #
 
-# Returns checked by default.
-return_unchecked=0
-# All items unchecked by default.
-all_checked=0
-# How many args there are to remove (the script is an argument itself, start with 1).
-options=1
-# Given items to show in the menu.
-items=()
-# All unchecked menu items.
-unchecked=()
-# All checked menu items.
-checked=()
-# Index of the item currently being hovered.
-hover_idx=0
-
 UNCHECKED_SYMBOL="[ ]"
 CHECKED_SYMBOL="[x]"
 
-function parse_args() {
-    for i in $@; do
-        case "$i" in
-            -u|--unchecked)
-                return_unchecked=1
-                ((options++))
-                ;;
-            -a|--all-checked)
-                all_checked=1
-                ((options++))
-                ;;
-            -*|--*)
-                echo "Unknown option $i"
-                exit 1
-                ;;
-            *)
-                break
-                ;;
-        esac
-    done
-}
+return_unchecked=1
+check_all=1
+items=()
+unchecked=()
+checked=()
+hover_idx=0
 
-function get_menu_items() {
-    echo "${@:$options}"
-}
-
-function in_list() {
-    local search_item="$1"
-    shift 1
-    local list=("$@")
-    for i in "${list[@]}"; do
-        [[ $search_item == $i ]] && return 0
-    done
-    return 1
-}
-
-# Add a checkbox to the menu-item. 
-function add_checkbox() {
-    local item="$1"
-    in_list "$item" "${checked[@]}" && echo "$CHECKED_SYMBOL $item" || echo "$UNCHECKED_SYMBOL $item"
-}
-
-function print_list() {
-    for i in "${!items[@]}"; do
-        local row=$(add_checkbox "${items[i]}")
-        # Highlight the item if index matches "selected" index.
-        if [[ $i -eq $hover_idx ]]; then
-            echo -e "\e[30;47m${row}\e[0m"
-        else
-            echo "$row"
-        fi
-    done
-}
-
-function input_parser() {
-    local escape=$'\x1b'
-    local up=$'[A'
-    local down=$'[B'
-    IFS= read -r -s -n1 key
-    case "$key" in
-        # Handle up/down keys by reading prefixed escape keys.
-        $escape)
-            read -r -s -n2 -t 0.05 next_chars
-            case $next_chars in
-                $up)
-                    echo "up"
-                    ;;
-                $down)
-                    echo "down"
-                    ;;
-            esac
-            ;;
-        " ")
-            echo "space"
-            ;;
-        "")
-            echo "enter"
-            ;;
-        "k")
-            echo "up"
-            ;;
-        "j")
-            echo "down"
-            ;;
-        "q"|"Q")
-            echo "exit"
-            ;;
-    esac
-}
-
-function shift_hover() {
+function shift_hover_idx() {
     local direction="$1"
     if [[ $direction == "up" ]]; then
         ((hover_idx--))
@@ -127,29 +29,139 @@ function shift_hover() {
     fi
 }
 
-function mark_selection() {
-    echo "selection marked"
+function in_list() {
+    local search_item="$1"
+    shift 1
+    local list=("$@")
+    for i in "${list[@]}"; do
+        [[ "$search_item" == "$i" ]] && return 0
+    done
+    return 1
 }
 
-function selection_loop() {
-    local selection_complete=0
-    local rows_count=$((${#items[@]} + 1))
-    local key=
-    until (( $selection_complete )); do
-        print_list
-        key=$(input_parser)
-        if [[ "$key" == "exit" ]]; then 
-            exit 0
-        elif [[ $key =~ ^(up|down)$ ]]; then
-            shift_hover "$key"
-        elif [[ $key == "space" ]]; then
-            mark_selection
-        elif [[ $key == "enter" ]]; then
-            selection_complete=1
+function index_of_list_item() {
+    local search_item="$1"
+    shift 1
+    local list=("$@")
+    for i in "${!list[@]}"; do
+        if [[ "$search_item" == "${list[i]}" ]];then
+            echo "$i"
+            return 0
         fi
-        echo -e "\033[${rows_count}A"
+    done
+    exit 1
+}
+
+function add_remove_selection() {
+    local item="${items[$hover_idx]}"
+    local item_idx=
+    if in_list "$item" "${checked[@]}"; then
+        unchecked+=("$item")
+        item_idx=$(index_of_list_item "$item" "${checked[@]}")
+        unset "checked[item_idx]"
+        checked=("${checked[@]}")
+    else
+        checked+=("$item")
+        item_idx=$(index_of_list_item "$item" "${unchecked[@]}")
+        unset "unchecked[item_idx]"
+        unchecked=("${unchecked[@]}")
+    fi
+}
+
+function highlight() {
+    echo -e "\e[30;47m${1}\e[0m"
+}
+
+function add_checkbox() {
+    local item="$1"
+    in_list "$item" "${checked[@]}" && echo "$CHECKED_SYMBOL $item" || echo "$UNCHECKED_SYMBOL $item"
+}
+
+function print_list() {
+    local row=
+    for i in "${!items[@]}"; do
+        row=$(add_checkbox "${items[i]}")
+        [[ $i -eq $hover_idx ]] && highlight "$row" || echo "$row"
     done
 }
+
+function parse_keypress() {
+    local escape_prefix=$'\x1b'
+    local up=$'[A'
+    local down=$'[B'
+    IFS= read -r -s -n1 key
+    case "$key" in
+        "k"|"K")
+            echo "up"
+            ;;
+        "j"|"J")
+            echo "down"
+            ;;
+        "q"|"Q")
+            echo "exit"
+            ;;
+        " ")
+            echo "space"
+            ;;
+        "")
+            echo "enter"
+            ;;
+        # Handle up/down keys by reading prefixed escape keys.
+        $escape_prefix)
+            read -r -s -n2 -t 0.05 next_chars
+            case $next_chars in
+                $up)
+                    echo "up"
+                    ;;
+                $down)
+                    echo "down"
+                    ;;
+            esac
+            ;;
+    esac
+}
+
+#==========================================#
+# Parse arguments, leaving the menu items. #
+#==========================================#
+
+while [[ $# -gt 0 ]]; do
+    case $1 in
+        # Default behaviour, but for explicity.
+        -c|--checked)
+            return_unchecked=1
+            shift 1
+            ;;
+        -u|--unchecked)
+            return_unchecked=0
+            shift 1
+            ;;
+        -a|--check-all)
+            check_all=0
+            shift 1
+            ;;
+        -*|--*)
+            echo "Unknown option $1" >&2
+            exit 1
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
+#============================================#
+# Handle if no items are given for the list. #
+#============================================#
+
+if [[ $# -eq 0 ]]; then
+    echo "Error: Items for the list is required." >&2
+    exit 1
+fi
+
+#========#
+# Setup. #
+#========#
 
 # Hide terminal cursor.
 tput civis
@@ -157,14 +169,33 @@ tput civis
 # Restore cursor on exit.
 trap 'tput cnorm; exit' INT TERM EXIT
 
-parse_args "$@"
-items=($(get_menu_items $@))
+items=("$@")
+[[ $check_all -eq 0 ]] && checked=("${items[@]}") || unchecked=("${items[@]}")
 
-# set initial selected or unselected items.
-if [[ $all_checked -eq 1 ]]; then
-    checked=items
-else
-    unchecked=items
-fi
+#=================#
+# Selection loop. #
+#=================#
 
-selection_loop
+selection_complete=1
+rows_count=$((${#items[@]} + 1))
+key=
+while [[ $selection_complete -eq 1 ]]; do
+    print_list
+    # Pauses loop, waiting for input.
+    key=$(parse_keypress)
+    if [[ "$key" == "exit" ]]; then 
+        exit 0
+    elif [[ $key =~ ^(up|down)$ ]]; then
+        shift_hover_idx "$key"
+    elif [[ $key == "space" ]]; then
+        add_remove_selection 
+    elif [[ $key == "enter" ]]; then
+        selection_complete=0
+    fi
+    # Prepare redraw; move cursor to top of list.
+    echo -e "\033[${rows_count}A"
+done
+
+[[ $return_unchecked -eq 0 ]] && echo "${unchecked[@]}" || echo "${checked[@]}"
+
+exit 0
