Some setps can be skipped, but warning is given

diff --git a/install b/install
--- a/install
+++ b/install
@@ -147,10 +147,11 @@ separator
 read -sp "Type your (sudo) password: " pass
 
 echo ""
+write_to_logfile ""
 
 # test the password, might pass due to correct password still being
 # valid from earlier don't know how to correct that.
-if ! echo "$pass" | sudo -S ls > /dev/null 2>> "$LOGGFILE_PATH"; then
+if ! echo "$pass" | sudo -S ls > /dev/null 2>&1; then
 	logging_warning "Incorrect password. Cancelling..."
 	exit 0
 fi
@@ -173,13 +174,13 @@ logging_ok "Verified connection"
 
 dist="Arch Linux"
 
-VSCODE_EXTENSION_PATH="/etc/os-release"
+path="/etc/os-release"
 logging_info "Checking if system is ${dist}..."
-if [[ ! -f "$VSCODE_EXTENSION_PATH" ]]; then
-	logging_error "Unable to locate [${VSCODE_EXTENSION_PATH}]: Not able to check if distro type is ${dist}. Cancelling..."
+if [[ ! -f "$path" ]]; then
+	logging_error "Unable to locate [${path}]: Not able to check if distro type is ${dist}. Cancelling..."
 	exit 1
 fi
-source "$VSCODE_EXTENSION_PATH"
+source "$path"
 
 if [[ "$ID" == "$DIST_ID" ]]; then
     logging_ok "System is ${dist}"
@@ -220,7 +221,7 @@ function create_symlink() {
 		logging_error "Error occurred while symlinking [${target_path}] -> [${source_path}]! Cancelling..."
 		exit 1
 	fi
-	logging_ok "Symlink created: [${target_conf_path}] -> [${source_path}]"
+	logging_ok "Symlink created: [${target_path}] -> [${source_path}]"
 }
 
 function item_in_list() {
@@ -262,16 +263,16 @@ separator
 #################### PACMAN INSTALL #################### 
 
 logging_info "Installing packages with [pacman]..."
-pacman_packages_len=$(wc -l "$PACMAN_PACKAGES_PATH" | awk '{print $1}')
 logging_info "Synchronizing packages (this might take some time)..."
 if ! echo "$pass" | sudo -S pacman -Sy > /dev/null 2>> "$LOGGFILE_PATH"; then
 	logging_error "Error occurred while synching packages! Cancelling..."
 	exit 1
 fi
 
+pacman_packages_len=$(wc -l "$PACMAN_PACKAGES_PATH" | awk '{print $1}')
 logging_info "Installing [${pacman_packages_len}] packages (this might take some time)..."
 mapfile -t pacman_packages < "$PACMAN_PACKAGES_PATH"
-if ! echo "$pass" | sudo -S pacman -S --needed --noconfirm "${pacman_packages[@]}" > /dev/null 2>> "$LOGGFILE_PATH"; then
+if ! echo "$pass" | sudo -S pacman -S --needed --noconfirm -- "${pacman_packages[@]}" > /dev/null 2>> "$LOGGFILE_PATH"; then
 	logging_error "Error occurred while installing [pacman] packages! Cancelling..."
 	exit 1
 fi
@@ -312,14 +313,8 @@ if ! type -p paru > /dev/null 2>> "$LOGGFILE_PATH"; then
 		exit 1
 	fi
 	cd "$temp_dir"
-	logging_info "Building [paru] with [makepkg] (this might take some time)..."
-	if ! makepkg -s > /dev/null 2>> "$LOGGFILE_PATH"; then
-		logging_error "Error occurred while building [paru]! Cleaning up then cancelling..."
-		cleanup
-		exit 1
-	fi
-	logging_info "Installing [paru] package with [makepkg]..."
-	if ! makepkg -i 2>> "$LOGGFILE_PATH"; then
+	logging_info "Building and installing [paru] package with [makepkg] (this might take some time)..."
+	if ! makepkg -sir 2>> "$LOGGFILE_PATH"; then
 		logging_error "Error occurred while installing [paru]! Cleaning up then cancelling..."
 		cleanup
 		exit 1
@@ -335,13 +330,12 @@ separator
 #################### PARU INSTALL ####################
 
 paru_packages_len=$(wc -l packages/paru.txt | awk '{print $1}')
-logging_info "Installing [${paru_packages_len}] packages (this might take some time)..."
+logging_info "Synching and Installing [${paru_packages_len}] packages (this might take some time)..."
 mapfile -t paru_packages < "$PARU_PACKAGES_PATH"
-if ! paru -S --needed --noconfirm "${paru_packages[@]}" > /dev/null 2>> "$LOGGFILE_PATH"; then
+if ! echo "$pass" | sudo -S paru -S --needed --noconfirm -- "${paru_packages[@]}" > /dev/null 2>> "$LOGGFILE_PATH"; then
 	logging_error "Error occurred when installing [paru] packages! Cancelling..."
 	exit 1
 fi
-logging_ok "Successfully installed [paru] packages"
 
 separator
 
@@ -350,30 +344,27 @@ separator
 logging_info "Enabling services..."
 mapfile -t services < "$SERVICES_PATH"
 if ! echo "$pass" | sudo -S systemctl enable --now "${services[@]}" > /dev/null 2>> "$LOGGFILE_PATH"; then
-	logging_warning "Error occurred while enabling service(s)! Cancelling..."
-	exit 1
+	logging_warning "Error occurred while enabling service(s)! Skipping..."
 fi
-logging_ok "Services enabled"
 
 separator
 
 #################### VSCODE ####################
 
-# install extensions
 logging_info "Installing [code-oss] extensions..."
-if ! cat "${VSCODE_EXTENSIONS_PATH}" | xargs -n 1 code --install-extension; then
-	logging_warning "Error occurred while installing [code-oss] extension(s)! Cancelling..."
-	exit 1
+if ! cat "${VSCODE_EXTENSIONS_PATH}" | xargs -n 1 code --install-extension > /dev/null 2>> "$LOGGFILE_PATH"; then
+	logging_warning "Error occurred while installing [code-oss] extension(s)! Skipping..."
+else
+	logging_ok "Successfully installed [code-oss] extensions"
 fi
-logging_ok "Successfully installed [code-oss] extensions"
 
-# link config
+logging_info "Linking [code-oss] settings file..."
 check_create_dir "$VSCODE_TARGET_PATH"
 if ! ln -s -- "$VSCODE_SOURCE_PATH" "$VSCODE_TARGET_PATH" 2>> "$LOGGFILE_PATH"; then
-	logging_error "Failed to link [code] settings file! Cancelling..."
-	exit 1
+	logging_warning "Failed to link [code-oss] settings file! Skipping..."
+else
+	logging_ok "Linked [code-oss] settings file"
 fi
-logging_ok "Linked [code] settings file"
 
 separator
 
@@ -382,10 +373,10 @@ separator
 # For permission to start up kvm/qemu.
 logging_info "Adding [${USER}] to [libvirt] group..."
 if ! echo "$pass" | sudo -S usermod -aG libvirt $USER 2>> "$LOGGFILE_PATH"; then
-	logging_error "Unable to add user to group! Cancelling..."
-	exit 1
+	logging_warning "Unable to add user to group! Skipping..."
+else
+	logging_ok "User added to group"
 fi
-logging_ok "User added to group"
 
 separator
 
@@ -393,10 +384,10 @@ separator
 
 logging_info "Symlinking [keyd] config..."
 if ! echo "$pass" | sudo -S ln -s -- "$KEYD_SOURCE_PATH" "$KEYD_TARGET_PATH"; then
-	logging_error "Error occurred while symlinking [keyd] config! Cancelling..."
-	exit 1
+	logging_warning "Error occurred while symlinking [keyd] config! Skipping..."
+else
+	logging_ok "[keyd] config symlinked"
 fi
-logging_ok "[keyd] config symlinked"
 
 separator
 
@@ -405,28 +396,43 @@ separator
 # Arch relies mostly on [org.gnome] for themes, instead of GTK / QT, and needs to be set
 logging_info "Setting icon theme to [${THEME}]..."
 if ! gsettings set org.gnome.desktop.interface icon-theme "$THEME" 2>> "$LOGGFILE_PATH"; then
-	logging_error "Error occurred while setting the icon theme! Cancelling..."
-	exit 1
+	logging_warning "Error occurred while setting the icon theme! Skipping..."
+else
+	logging_ok "[${THEME}] icon theme set successfully"
 fi
+
+separator
 
 #################### NEOVIM SETUP ####################
 
-logging_info "Cloning [nvim-treesitter] repo..."
-if ! git clone --depth=1 -- "$TS_URL" "$HOME" > /dev/null 2>> "$LOGGFILE_PATH"; then
-	logging_error "Failed to clone [nvim-treesitter]! Cancelling..."
-	exit 1
-fi
+function clone_ts_repo() {
+	logging_info "Cloning [nvim-treesitter] repo..."
+	if ! git clone --depth=1 -- "$TS_URL" "$HOME" > /dev/null 2>> "$LOGGFILE_PATH"; then
+		logging_warning "Failed to clone [nvim-treesitter]! Skipping..."
+		return 1
+	fi
+	return 0
+}
 
-logging_info "Copying [nvim-treesitter] queries into [neovim] config..."
-if ! cp -r -- "$NVIM_TREE_SITTER_QUERIES_SOURCE_PATH" "$NVIM_TREE_SITTER_QUERIES_TARGET_PATH" 2>> "$LOGGFILE_PATH"; then
-	logging_error "Failed to copy from [${NVIM_TREE_SITTER_QUERIES_SOURCE_PATH}] to [${NVIM_TREE_SITTER_QUERIES_TARGET_PATH}]! Cancelling..."
-	exit 1
-fi
+function copy_ts_queries() {
+	logging_info "Copying [nvim-treesitter] queries into [neovim] config..."
+	if ! cp -r -- "$NVIM_TREE_SITTER_QUERIES_SOURCE_PATH" "$NVIM_TREE_SITTER_QUERIES_TARGET_PATH" 2>> "$LOGGFILE_PATH"; then
+		logging_warning "Failed to copy from [${NVIM_TREE_SITTER_QUERIES_SOURCE_PATH}] to [${NVIM_TREE_SITTER_QUERIES_TARGET_PATH}]! Skipping..."
+		return 1
+	fi
+	return 0
+}
 
-logging_info "Deleting [nvim-treesitter] repo..."
-if ! rm -rf -- "$NVIM_TREE_SITTER_DOWNLOAD_PATH" 2>> "$LOGGFILE_PATH"; then
-	logging_warning "Not able to delete [${NVIM_TREE_SITTER_DOWNLOAD_PATH}]! Skipping..."
-fi
+function delete_ts_repo() {
+	logging_info "Deleting [nvim-treesitter] repo..."
+	if ! rm -rf -- "$NVIM_TREE_SITTER_DOWNLOAD_PATH" 2>> "$LOGGFILE_PATH"; then
+		logging_warning "Not able to delete [${NVIM_TREE_SITTER_DOWNLOAD_PATH}]! Skipping..."
+		return 1
+	fi
+	return 0
+}
+
+clone_ts_repo && copy_ts_queries && delete_ts_repo
 
 separator
 
